baseURL = 'https://templedss.github.io/LEADING/'
languageCode = 'en-us'
title = 'Mapping Black Philly Art'
theme = "ananke"
canonifyURL = true

[menu]
    [[menu.main]]
    identifier = "syllabus"
    name       = "Syllabus"
    url        = "/syllabus/"
    weight     = 1

    [[menu.main]]
    identifier = "resources"
    name       = "Resources"
    url        = "/resources/"
    weight     = 2

    [[menu.main]]
    identifier = "people"
    name       = "People"
    url        = "/people/"
    weight     = 3